#!/usr/bin/env python3
"""Score the merged full-corpus annotation against GT.

After both `--full-corpus-1` and `--full-corpus-2` jobs complete and
`merge_full_corpus_results.py` produces a unified output, this script
computes per-field accuracy on the full 630-NCT training universe and
compares it to the production-gate measurement (Job #101) — sanity
check that the agent's full-corpus accuracy matches the gate's CI.

Inputs:
  - JOB_ID_1 + JOB_ID_2: the two batch job IDs (must be completed)
  - OR: --merged-json <path> to skip job loading and use the merge
    output directly

Outputs (stdout):
  - Per-field: hits / scoreable / accuracy / 95% CI
  - Δ vs production-gate (Job #101): each field's full-corpus accuracy
    vs gate accuracy. Difference >2σ is a CI violation.
  - Per-outcome-class breakdown (positive / unknown / terminated /
    failed / withdrawn) — first time this is measured at full scale

Per CONTINUATION_PLAN production goals: full-corpus IS the publication-
grade output. Use these numbers as the canonical accuracy benchmark
for the system's deployment claims.

Usage:
  # After merge_full_corpus_results.py:
  python3 scripts/score_full_corpus.py --merged-json scripts/full_corpus_merged_2172018e.json

  # Or directly from job IDs (re-merges in memory):
  python3 scripts/score_full_corpus.py JOB_ID_1 JOB_ID_2
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from collections import Counter
from pathlib import Path

PROD_JSON = Path(
    "/Users/amphoraxe/Developer/amphoraxe/llm.amphoraxe.ca/amp_llm_v3/"
    "standalone modules/agent_annotate/results/json"
)
PKG_ROOT = Path(__file__).resolve().parents[1]
GT_PATH = PKG_ROOT / "docs" / "human_ground_truth_train_df.csv"

GT_COLS = {
    "classification": ("Classification_ann1", "Classification_ann2"),
    "peptide": ("Peptide_ann1", "Peptide_ann2"),
    "delivery_mode": ("Delivery Mode_ann1", "Delivery Mode_ann2"),
    "outcome": ("Outcome_ann1", "Outcome_ann2"),
    "reason_for_failure": ("Reason for Failure_ann1", "Reason for Failure_ann2"),
}

PER_FIELD_TARGETS = {
    "classification": 0.95,
    "peptide": 0.85,
    "delivery_mode": 0.80,
    "outcome": 0.65,
    "sequence": 0.50,
    "reason_for_failure": 0.95,
}


def norm(s: str) -> str:
    return (s or "").strip().lower()


def consensus(a: str, b: str) -> str | None:
    a, b = norm(a), norm(b)
    if a and b:
        return a if a == b else None
    return a or b or None


def wald_hw(p: float, n: int) -> float:
    if n == 0:
        return float("nan")
    return 1.96 * math.sqrt(p * (1 - p) / n)


def get_field(trial: dict, name: str) -> dict | None:
    for a in trial.get("annotations", []) or []:
        if isinstance(a, dict) and a.get("field_name") == name:
            return a
    return None


def load_gt() -> dict[str, dict]:
    gt = {}
    with GT_PATH.open() as f:
        for r in csv.DictReader(f):
            nct = (r.get("nct_id") or "").upper().strip()
            if not nct:
                continue
            gt[nct] = {
                field: consensus(r.get(c1, ""), r.get(c2, ""))
                for field, (c1, c2) in GT_COLS.items()
            }
            gt[nct]["_raw_seq_r1"] = (r.get("Sequence_ann1") or "").strip()
            gt[nct]["_raw_seq_r2"] = (r.get("Sequence_ann2") or "").strip()
    return gt


def load_trials(args) -> list[dict]:
    if args.merged_json:
        path = Path(args.merged_json)
        if not path.exists():
            raise SystemExit(f"merged JSON not found: {path}")
        data = json.load(path.open())
        return data.get("trials", [])
    elif args.job_ids:
        all_trials = []
        seen: set[str] = set()
        for jid in args.job_ids:
            p = PROD_JSON / f"{jid}.json"
            if not p.exists():
                raise SystemExit(f"job result not found: {p}")
            d = json.load(p.open())
            for t in d.get("trials", []) or d.get("results", []) or []:
                nct = (t.get("nct_id") or "").upper()
                if nct in seen:
                    continue
                seen.add(nct)
                all_trials.append(t)
        return all_trials
    else:
        raise SystemExit("must provide either job_ids or --merged-json")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("job_ids", nargs="*", help="batch 1 + batch 2 job IDs")
    ap.add_argument("--merged-json", help="path to a merge_full_corpus_results.py output")
    ap.add_argument("--gate-job", default="826f2608ddd8",
                    help="production-gate job ID to compare against (default: Job #101)")
    args = ap.parse_args()

    trials = load_trials(args)
    gt = load_gt()
    print(f"Loaded {len(trials)} trials. Scoring against {len(gt)} GT entries.\n",
          file=sys.stderr)

    print("# Full-corpus accuracy report\n")
    print(f"_Auto-generated by `scripts/score_full_corpus.py` over {len(trials)} unique NCTs._\n")

    print("## Per-field accuracy on full corpus\n")
    print("| Field | Target | Full-corpus | 95% CI | Status |")
    print("|---|---|---|---|---|")
    full_results: dict[str, dict] = {}
    sys.path.insert(0, str(PKG_ROOT))
    from app.services.concordance_service import sequences_match

    for field, target in PER_FIELD_TARGETS.items():
        hits = 0
        n = 0
        for t in trials:
            nct = (t.get("nct_id") or "").upper()
            ann = get_field(t, field) or {}
            pred = (ann.get("value") or "").strip()
            if not pred:
                continue
            if field == "sequence":
                gt_entry = gt.get(nct, {})
                gt_seq = gt_entry.get("_raw_seq_r1") or gt_entry.get("_raw_seq_r2")
                if not gt_seq or gt_seq.lower() in ("n/a", "na"):
                    continue
                if pred.lower() in ("n/a", "na"):
                    n += 1
                    continue
                n += 1
                if sequences_match(gt_seq, pred):
                    hits += 1
            else:
                gt_v = (gt.get(nct, {}) or {}).get(field)
                if not gt_v:
                    continue
                n += 1
                if norm(pred) == gt_v:
                    hits += 1
        p = hits / n if n else 0
        hw = wald_hw(p, n) if n else float("nan")
        emoji = "✅" if p >= target else ("⚠️" if p >= target - 0.05 else "❌")
        ci_str = f"±{hw*100:.1f}pp" if n else "n/a"
        print(f"| {field} | ≥{int(target*100)}% | {hits}/{n} = {p*100:.1f}% | {ci_str} | {emoji} |")
        full_results[field] = {"hits": hits, "n": n, "p": p, "hw": hw}
    print()

    # Outcome by class
    by_class: dict[str, dict] = {}
    for t in trials:
        nct = (t.get("nct_id") or "").upper()
        ann = get_field(t, "outcome") or {}
        pred = norm(ann.get("value", ""))
        gt_v = (gt.get(nct, {}) or {}).get("outcome")
        if not gt_v or not pred:
            continue
        d = by_class.setdefault(gt_v, {"n": 0, "hits": 0})
        d["n"] += 1
        if pred == gt_v:
            d["hits"] += 1

    print("## Outcome stratified by GT class\n")
    print("| GT outcome | n | hits | accuracy |")
    print("|---|---|---|---|")
    for cls in ("positive", "unknown", "terminated", "failed - completed trial", "withdrawn"):
        d = by_class.get(cls, {"n": 0, "hits": 0})
        n = d["n"]
        acc = d["hits"] / n * 100 if n else 0
        print(f"| {cls} | {n} | {d['hits']} | {acc:.1f}% |")
    print()

    print("## Methodology disclosure\n")
    print(
        f"- **Trials scored:** {len(trials)} unique NCTs from the full 630-NCT training universe (training_csv − test_batch).\n"
        "- **GT consensus rule:** R1==R2, OR only one annotator filled in.\n"
        "- **Sequence scoring:** `sequences_match` set-containment (canonicaliser strips terminal -OH/-NH₂ chemistry suffixes per v42.7.16).\n"
        f"- **Comparison to production gate ({args.gate_job}):** if available, score that job with the same methodology and verify full-corpus accuracy is within the gate's ±6.3pp CI for outcome.\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
